// <auto-generated />
namespace Organics.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class fiexd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fiexd));
        
        string IMigrationMetadata.Id
        {
            get { return "201304190245035_fiexd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
